title: Rambling of a number

description: This is where i'll write whatever I want to talk about
url: "https://0xdouze.github.io/"
lsi: false
author: Kevin Tavukciyan

theme: jekyll-theme-cayman

permalink: pretty
